language: cpp

git:
  submodules: false

compiler:
    - gcc
    - clang

before_install:
    - sed -i 's/git@github.com:/git:\/\/github.com\//' .gitmodules
    - git submodule init
    - git submodule sync
    - git submodule update

install:
    - export COMPILER=$CC
    - sudo apt-get install libboost-all-dev libbz2-dev libssl-dev python-dev uuid-dev
    - if [ "$CXX" = "g++" ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; sudo apt-get update; sudo apt-get install -qq g++-4.8; export CXX="g++-4.8" CC="gcc-4.8"; fi
    - Boost/install $(lsb_release -cs)

script:
    - ./build toolset=$COMPILER -q

matrix:
    allow_failures:
        - compiler: gcc
