language: cpp

git:
  submodules: false

before_install:
    - sed -i 's/git@github.com:/git:\/\/github.com\//' .gitmodules
    - git submodule init
    - git submodule sync
    - git submodule update

install:
    - sudo apt-get install libboost-all-dev

script:
    - ./build
