#!/bin/bash
cd `dirname $0`
svn up .

if [ ! -e fost-web ]
then
    git clone git@github.com:Felspar/fost-web.git
    cd fost-web
    git pull
    git flow init -d
    git pull
    cd ..
else
    cd fost-web
    git pull
    cd ..
fi

fost-meta/compile $*
