#!/bin/bash
cd `dirname $0`/..

svn co http://svn.felspar.com/external/Boost
svn co http://svn.felspar.com/public/fost-base/trunk fost-base
svn co http://svn.felspar.com/public/fost-internet/trunk fost-internet
svn co http://svn.felspar.com/public/fost-orm/trunk fost-orm
svn co http://svn.felspar.com/public/fost-postgres/trunk fost-postgres
svn co http://svn.felspar.com/external/PostgreSQL PostgreSQL && cd PostgreSQL && ./configure && cd ..
svn co http://svn.felspar.com/public/fost-py/trunk fost-py
svn co http://svn.felspar.com/public/fost-windows/trunk fost-windows

svn co http://svn.felspar.com/public/AppServiceSDK/trunk AppServiceSDK

svn co http://svn.felspar.com/public/spruce/trunk spruce
