#!/bin/bash
cd `dirname $0`/..

BRANCH=${1:-trunk}

svn co http://svn.felspar.com/external/Boost
svn co http://svn.felspar.com/public/fost-base/$BRANCH fost-base
svn co http://svn.felspar.com/public/fost-internet/$BRANCH fost-internet
svn co http://svn.felspar.com/public/fost-orm/$BRANCH fost-orm
svn co http://svn.felspar.com/public/fost-postgres/$BRANCH fost-postgres
svn co http://svn.felspar.com/external/PostgreSQL PostgreSQL && PostgreSQL/configure
svn co http://svn.felspar.com/public/fost-py/$BRANCH fost-py
svn co http://svn.felspar.com/public/fost-windows/$BRANCH fost-windows

svn co http://svn.felspar.com/public/AppServiceSDK/$BRANCH appservicesdk

svn co http://svn.felspar.com/public/spruce/$BRANCH spruce
