#!/bin/bash
cd `dirname $0`

if test -e /proc/
then {
    export CPUCOUNT=`grep -c ^processor /proc/cpuinfo`
    export TOOLSET=gcc
} else {
    export CPUCOUNT=1
    export TOOLSET=darwin
    export DYLD_LIBRARY_PATH=../dist/lib
    export LANG=C
    export LC_CTYPE="C"
}
fi

if ../bjam -j$CPUCOUNT toolset=$TOOLSET $* `../python.opts.sh`
then {
    echo fost-meta $* OK
    exit 0
} else {
    exit 1
}
fi
