#!/usr/bin/env bash
cd $(dirname $0)
set -ex

TAG=$(git describe --dirty)
UBUNTU=bionic

function dockerize {
    docker build --file $1.dockerfile \
        --build-arg TAG=$TAG \
        --build-arg UBUNTU=$UBUNTU \
        --tag fost/$1:$TAG .
    docker push fost/$1:$TAG
}
function latest {
    docker tag fost/$1:$TAG fost/$1:latest
    docker push fost/$1:latest
}

docker pull ubuntu:$UBUNTU
dockerize ubuntu; latest ubuntu
dockerize builder; latest builder
dockerize runtime; latest runtime

