#!/usr/bin/env bash
cd $(dirname $0)

set -ex

RELEASE=bionic

# Make sure we have the latest source image
for IMAGE in fost-runtime fost-builder; do
    sudo docker pull kayess/$IMAGE:$RELEASE
done

# Compile the code
mkdir -p ../tmp/$RELEASE/{build.tmp,dist}
rm -rf  ../tmp/$RELEASE/dist/*
sudo docker run -u $(id -u):$(id -g)  \
    -v $(pwd)/..:/src \
    -v $(pwd)/../tmp/$RELEASE/build.tmp:/src/build.tmp \
    -v $(pwd)/../tmp/$RELEASE/dist:/src/dist \
    -it --rm=true kayess/fost-builder:$RELEASE \
        bash -c -- "cd build.tmp && \
            cmake -G Ninja \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_INSTALL_PREFIX=../dist \
                .. && \
            ninja install/strip"
cp mengmom/Dockerfile ../tmp/$RELEASE/dist/
sed -i s/:latest/:${RELEASE}/ ../tmp/$RELEASE/dist/Dockerfile
sudo docker build -t kayess/mengmom:$RELEASE ../tmp/$RELEASE/dist/
sudo docker push kayess/mengmom:$RELEASE

sudo docker tag kayess/mengmom:$RELEASE kayess/mengmom:latest
sudo docker push kayess/mengmom:latest

VERSION=$(git describe --dirty)
sudo docker tag kayess/mengmom:$RELEASE kayess/fostgres:$VERSION
sudo docker push kayess/fostgres:$VERSION

if git branch | grep "* master" > /dev/null
then {
    sudo docker tag kayess/fostgres:$VERSION kayess/fostgres:latest
    sudo docker push kayess/fostgres:latest
}
fi

