#!/usr/bin/env bash
cd $(dirname $0)
set -ex

TAG=$(git describe --dirty)

rm -rf dist build.tmp

sudo docker pull fost/builder:latest
sudo docker pull fost/runtime:latest

# Build software and leave in `dist` folder
sudo docker run -it --rm -u $(id -u):$(id -g) -w /src/ \
    -v $(pwd)/..:/src \
    fost/builder bash -c \
        "mkdir -p docker/build.tmp && \
            cd docker/build.tmp && \
            cmake -G Ninja \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_INSTALL_PREFIX=../dist \
                /src/  && \
            ninja install/strip"

sudo docker build --no-cache --file all.dockerfile \
        --tag fost/all:$TAG .
sudo docker push fost/all:$TAG

if git branch | grep "* master" > /dev/null
then {
    sudo docker tag fost/all:$TAG fost/all:latest
    sudo docker push fost/all:latest
}
fi
