#!/usr/bin/env bash
cd $(dirname $0)
set -ex

TAG=$(git describe --dirty)
UBUNTU=bionic


function dockerize {
    sudo docker build --no-cache \
        --build-arg TAG=$TAG \
        --build-arg UBUNTU=$UBUNTU \
        --tag fost/$1:$TAG $1
    sudo docker push fost/$1:$TAG
}

sudo docker pull ubuntu:$UBUNTU
dockerize ubuntu
dockerize builder
dockerize minit
dockerize runtime

sudo docker build --no-cache \
        --build-arg TAG=$TAG \
        --file all/Dockerfile \
        --tag fost/all:$TAG ..
sudo docker push fost/all:$TAG

