name: fost
#base: core18
version: ignored
version-script: git describe --dirty

summary: Fost development tools
description: |
  Development tools etc. for Fost

grade: devel
confinement: devmode

parts:
    locales-launch:
    fost:
        source: .
        plugin: cmake
        configflags:
        - -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_INSTALL_PREFIX=/
          -DSKIP_PYTHON=YES
        stage-packages: [libstdc++6, locales-all, libpq5]
    odin-python:
        source: odin
        plugin: python
        python-version: python3

apps:
  fostgres-test:
    command: locales-launch fostgres-test
  fost-webserver:
    command: locales-launch fost-webserver
  json-schema-validator:
    command: locales-launch json-schema-validator
  odin:
    command: locales-launch odin
  odin-hash-rounds:
    command: locales-launch odin-hash-rounds
  pgasio-csj:
    command: locales-launch pgasio-csj
  pgasio-stats:
    command: locales-launch pgasio-stats
  wright-exec-helper:
    command: locales-launch wright-exec-helper

