name: fost
#base: core18
version: ignored
version-script: git describe --dirty

summary: Fost development tools
description: |
  Development tools etc. for Fost

grade: devel
confinement: devmode

parts:
    fost:
        source: .
        plugin: cmake
        configflags:
        - -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_INSTALL_PREFIX=/
        stage-packages: [libpq5]
