name: fost
base: core18
version: ignored
version-script: git describe

summary: Fost development tools
description: |
  Development tools etc. for Fost

grade: devel
confinement: devmode

parts:
    fost:
        source: .
        plugin: cmake
        build-packages:
          - g++
          - libssl-dev
          - libpq-dev
          - postgresql-server-dev-all
